#' Collect and present the results of the quality assessment of short reads
#' @description A high-level function for consolidating and presenting the
#'     results of quality assessment of short reads generated by the function
#'     assessQRawReads().
#' @param x character string specifying the name of object developed by the
#'     function assessQRawReads().
#' @param output character string that specifying a postfix for naming all
#'     output report files. The default value is NULL, at which the name of
#'     sample will be used for naming all output files.
#' @param workDir character string specifying the path to and name of working
#'     directory. NULL by default that means the current working directory.
#' @return a series of text and graphic files.
#' @author Vasily V. Grinev
#' @examples
#' report <- reportQAResults(x=qa,
#'                           output=NULL,
#'                           workDir="D:/Vasily Grinev")
#' @export
#' Last updated: July 17, 2025.

reportQAResults <- function(x,
                            output=NULL,
                            workDir=NULL){
    ### Loading the required packages.
    #   This code was successfully tested with packages Biostrings v.2.72.1,
    #   grid, gridExtra v.2.3, pheatmap v.1.0.12, pwalign v.1.4.0
    #   and vioplot v.0.5.0.
    suppressMessages(expr=library(package=Biostrings))
    suppressMessages(expr=library(package=grid))
    suppressMessages(expr=library(package=gridExtra))
    suppressMessages(expr=library(package=pheatmap))
    suppressMessages(expr=library(package=pwalign))
    suppressMessages(expr=library(package=vioplot))
    ### Textual reports.
    ##  Template of textual table.
    tab <- data.frame(Parameter=c("Sample name",
                                  "File name",
                                  "Total number of reads",
                                  "Total number of bases",
                                  "Length of reads, min",
                                  "Length of reads, 1st quartile",
                                  "Length of reads, median",
                                  "Length of reads, 3rd quartile",
                                  "Length of reads, max",
                                  "Per entire reads quality, min",
                                  "Per entire reads quality, 1st quartile",
                                  "Per entire reads quality, median",
                                  "Per entire reads quality, 3rd quartile",
                                  "Per entire reads quality, max",
                                  "Frequency of A, min",
                                  "Frequency of A, 1st quartile",
                                  "Frequency of A, median",
                                  "Frequency of A, 3rd quartile",
                                  "Frequency of A, max",
                                  "Frequency of C, min",
                                  "Frequency of C, 1st quartile",
                                  "Frequency of C, median",
                                  "Frequency of C, 3rd quartile",
                                  "Frequency of C, max",
                                  "Frequency of G, min",
                                  "Frequency of G, 1st quartile",
                                  "Frequency of G, median",
                                  "Frequency of G, 3rd quartile",
                                  "Frequency of G, max",
                                  "Frequency of T, min",
                                  "Frequency of T, 1st quartile",
                                  "Frequency of T, median",
                                  "Frequency of T, 3rd quartile",
                                  "Frequency of T, max",
                                  "Frequency of N, min",
                                  "Frequency of N, 1st quartile",
                                  "Frequency of N, median",
                                  "Frequency of N, 3rd quartile",
                                  "Frequency of N, max",
                                  "Frequency of GC, min",
                                  "Frequency of GC, 1st quartile",
                                  "Frequency of GC, median",
                                  "Frequency of GC, 3rd quartile",
                                  "Frequency of GC, max",
                                  "Low-complexity of reads, min",
                                  "Low-complexity of reads, 1st quartile",
                                  "Low-complexity of reads, median",
                                  "Low-complexity of reads, 3rd quartile",
                                  "Low-complexity of reads, max"),
                      Value=0) 
    ##  Values of textual table.
    tab[1, 2] <- x$SN
    tab[2, 2] <- x$FN
    tab[3, 2] <- x$TNRs
    tab[4, 2] <- x$TNBs
    tab[5:9, 2] <- x$RLs[-4]
    tab[10:14, 2] <- sprintf(x=x$PERQs$metrics, fmt="%.1f")
    tab[15:39, 2] <- formatC(x=c(t(x$BCs$metrics[, -1])), format="e", digits=2)
    tab[40:44, 2] <- formatC(x=x$GCs$metrics, format="e", digits=2)
    tab[45:49, 2] <- x$DSs$metrics
    ##  Saving of textual table as *.PDF file.
    if (is.null(x=output)){
        file_output <- paste(sprintf("QA metrics of %s", x$SN),
                             "pdf",
                             sep=".")
    }else{
        file_output <- paste(sprintf("QA metrics of %s", output),
                             "pdf",
                             sep=".")
    }
    pdf(file=paste(workDir, file_output, sep="/"), height=nrow(x=tab)/3)
    theme=ttheme_minimal(core=list(fg_params=list(hjust=0,
                                                  x=0.03,
                                                  fontsize=10),
                                   bg_params=list(fill=rep(c("azure1",
                                                             "azure3"),
                                                           each = 1),
                                                           col="black")),
                         colhead=list(fg_params=list(col="white"),
                                      bg_params=list(fill="darkcyan",
                                                     col="black")))
    table <- tableGrob(d=tab, rows=NULL, theme=theme)
    title1 <- textGrob(label="Quality of the raw reads. Summary statistics",
                       just="centre",
                       vjust=-60,
                       gp=gpar(col="black",
                               font=2,
                               fontsize=12))
    title2 <- textGrob(label=sprintf("Sample: %s", x$SN),
                       just="centre",
                       vjust=-63.5,
                       gp=gpar(col="black",
                               fontsize=11))
    title3 <- textGrob(label=sprintf(paste("Date & Time:",
                                     format(x=Sys.time(), "%b %d %Y %X"),
                                     sep=" ")),
                       just="centre",
                       vjust=-67.8,
                       gp=gpar(col="black",
                               fontsize=10))
    note <- "Generated by assessQRawReads() & reportQAResults()"
    note <- textGrob(label=sprintf(note),
                     just="centre",
                     vjust=88,
                     gp=gpar(col="black",
                             fontsize=8))
    gt <- gTree(children=gList(table, title1, title2, title3, note))
    grid.draw(gt)
    suppressMessages(expr=dev.off())
    ##  Saving of overrepresented reads.
    ORs <- DNAStringSet(x=x$ORs$sequence)
    names(x=ORs) <- paste(paste("seq",
                                formatC(x=1:length(x=x$ORs$sequence),
                                width=4, flag="0"), sep=""),
                          x$ORs$count, sep=", ")
    if (is.null(x=output)){
        file_output <- paste(sprintf("Overrepresented reads of %s", x$SN),
                             "fasta",
                             sep=".")
    }else{
        file_output <- paste(sprintf("Overrepresented reads of %s", output),
                             "fasta",
                             sep=".")
    }
    writeXStringSet(x=ORs,
                    filepath=paste(workDir, file_output, sep="/"),
                    format="fasta")
    ### Graphical reports.
    ##  Per entire reads quality plots.
    if (is.null(x=output)){
        file_output <- paste(sprintf("QA plots of %s", x$SN),
                             "pdf",
                             sep=".")
    }else{
        file_output <- paste(sprintf("QA plots of %s", output),
                             "pdf",
                             sep=".")
    }
    pdf(file=paste(workDir, file_output, sep="/"),
        onefile=TRUE,
        paper="a4",
        width=8.27, height=11.69)
    par(mfrow=c(3, 2),
        omi=c(0.79, 0.79, 1, 0.79))
    plot(0, type="n", axes=FALSE, ann=FALSE, bty="n",
         xlim=c(0, 2), ylim=c(0, 40))
    vioplot(x=x$PERQs$means[1:10000],
            add=TRUE,
            col=rgb(red=86, green=180, blue=233, maxColorValue=255),
            rectCol=rgb(red=0, green=158, blue=115, maxColorValue=255),
            pchMed=0, colMed=NA,
            lwd=0.9,
            wex=1,
            frame.plot=FALSE)
    segments(x0=0.9, y0=median(x=x$PERQs$means),
             x1=1.1, y1=median(x$PERQs$means),
             col=rgb(red=240, green=228, blue=66, maxColorValue=255),
             lwd=3, lend=2)
    axis(side=1, at=c(0, 1, 2), labels=FALSE, lwd=0.8)
    axis(side=2, at=c(0, 10, 20, 30, 40), labels=c(0, 10, 20, 30, 40),
         las=1, lwd=0.8)
    title(main="Distribution of reads quality", cex.main=1.5)
    title(xlab="Standard vioplot", line=1, cex.lab=1.2)
    title(ylab="Average read quality scores", line=2.3, cex.lab=1.2)
    per <- data.frame(threshold=0:ceiling(x=max(x=x$PERQs$means)), percent=0)
    per[1, 2] <- 100
    L <- length(x=x$PERQs$means)
    for (i in 1:ceiling(x=max(x=x$PERQs$means))){
        p <- length(x=x$PERQs$means[x$PERQs$means > i])/L * 100
        per[i + 1, 2] <- round(x=p, digits=1)
    }
    plot(per, type="l", bty="n",
         xlim=c(0, 40), ylim=c(0, 100),
         lwd=1,
         col=rgb(red=0, green=114, blue=178, maxColorValue=255),
         ann=FALSE, axes=FALSE)
    axis(side=1,
         at=c(0, 10, 20, 30, 40),
         labels=c(0, 10, 20, 30, 40),
         las=1, lwd=0.8)
    axis(side=2,
         at=c(0, 20, 40, 60, 80, 100),
         labels=c(0, 20, 40, 60, 80, 100),
         las=1, lwd=0.8)
    title(main="Thresholding of reads quality", cex.main=1.5)
    title(xlab="Quality threshold", line=2.5, cex.lab=1.2)
    title(ylab="Reads exceeding quality level, %", line=2.8, cex.lab=1.2)
    rect(xleft=0, ybottom=0, xright=20, ytop=100, border=NA,
         col=rgb(red=240, green=228, blue=66, maxColorValue=255, alpha=40))
    rect(xleft=20, ybottom=0, xright=30, ytop=100, border=NA,
         col=rgb(red=230, green=159, blue=0, maxColorValue=255, alpha=40))
    rect(xleft=30, ybottom=0, xright=40, ytop=100, border=NA,
         col=rgb(red=213, green=94, blue=0, maxColorValue=255, alpha=70))
    text(x=20, y=20, srt=90,
         labels=paste(paste("Q20",
                            round(x=length(x=x$PERQs$means[x$PERQs$means >
                                                       20])/L * 100, digits=1),
                            sep=", "),
                      "%",
                      sep=""))
    text(x=30, y=20, srt=90,
         labels=paste(paste("Q30",
                            round(x=length(x=x$PERQs$means[x$PERQs$means >
                                                       30])/L * 100, digits=1),
                            sep=", "),
                      "%",
                      sep=""))
    ##  Per cycle reads quality plots.
    bxp(z=list(stats=t(x$PCQRs[, -1]),
        n=rep(x=length(x=x$PERQs$means), times=nrow(x=x$PCQRs))),
        ylim=c(0, 40),
        boxfill=rgb(red=240, green=228, blue=66, maxColorValue=255),
        frame=FALSE,
        axes=FALSE,
        lwd=0.6,
        medlwd=1, medcol=rgb(red=204, green=121, blue=167, maxColorValue=255),
        whisklty="solid")
    axis(side=1,
         at=1:length(x=x$PCQRs[, 1]),
         labels=FALSE,
         las=2, lwd=0.8)
    axis(side=2,
         at=c(0, 10, 20, 30, 40),
         labels=c(0, 10, 20, 30, 40),
         las=1, lwd=0.8)
    text(x=seq(from=1, to=length(x=x$PCQRs[, 1]), by=2),
         par("usr")[3] - 3, offset=-0.5, cex=0.9,
         labels=x$PCQRs[, 1][seq(from=1, to=length(x=x$PCQRs[, 1]), by=2)],
         srt=55, pos=2, xpd=TRUE)
    title(main="Per cycle quality of reads", cex.main=1.5)
    title(xlab="Cycles", line=3.7, cex.lab=1.2)
    title(ylab="Quality scores across of all bases", line=2.3, cex.lab=1.2)
    rect(xleft=0.5, ybottom=0, xright=length(x=x$PCQRs[, 1]) + 0.5, ytop=20,
         border=NA,
         col=rgb(red=240, green=228, blue=66, maxColorValue=255, alpha=40))
    rect(xleft=0.5, ybottom=20, xright=length(x=x$PCQRs[, 1]) + 0.5, ytop=30,
         border=NA,
         col=rgb(red=230, green=159, blue=0, maxColorValue=255, alpha=40))
    rect(xleft=0.5, ybottom=30, xright=length(x=x$PCQRs[, 1]) + 0.5, ytop=40,
         border=NA,
         col=rgb(red=213, green=94, blue=0, maxColorValue=255, alpha=70))
    ##  Base composition of the entire set of reads.
    colrs <- c(rgb(red=0, green=114, blue=178, maxColorValue=255),
               rgb(red=213, green=94, blue=0, maxColorValue=255),
               rgb(red=86, green=180, blue=233, maxColorValue=255),
               rgb(red=230, green=159, blue=0, maxColorValue=255),
               rgb(red=204, green=121, blue=167, maxColorValue=255))
    bxp(z=list(stats=t(x$BCs$metrics[, -1]),
        n=rep(x=length(x=x$PERQs$means), times=nrow(x=x$BCs$metrics))),
        ylim=c(0, 0.5),
        boxfill=colrs,
        frame=FALSE,
        axes=FALSE,
        lwd=0.6,
        medlwd=1,
        boxwex=0.6,
        whisklty="solid")
    axis(side=1,
         at=c(1, 2, 3, 4, 5),
         labels=x$BCs$metrics[, 1],
         las=1, lwd=0.8)
    axis(side=2,
         at=c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5),
         labels=c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5),
         las=2, lwd=0.8)
    title(main="Base composition of reads", cex.main=1.5)
    title(xlab="Base", line=2.5, cex.lab=1.2)
    title(ylab="Frequency", line=2.8, cex.lab=1.2)
    ##  Per cycle base composition of reads.
    matplot(x$PCCBs[, -1],
            type="l", lty=1, lwd=1, col=colrs,
            ylim=c(0, 1),
            ann=FALSE, axes=FALSE)
    axis(side=1,
         at=1:length(x=x$PCCBs[, 1]),
         labels=FALSE,
         las=2, lwd=0.8)
    axis(side=2,
         at=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         labels=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         las=1, lwd=0.8)
    text(x=seq(from=1, to=length(x=x$PCCBs[, 1]), by=2),
         par("usr")[3] - 0.08, offset=-0.5, cex=0.9,
         labels=x$PCCBs[, 1][seq(from=1, to=length(x=x$PCCBs[, 1]), by=2)],
         srt=55, pos=2, xpd=TRUE)
    title(main="Per cycle composition of reads", cex.main=1.5)
    title(xlab="Cycles", line=3.8, cex.lab=1.2)
    title(ylab="Base frequency", line=2.3, cex.lab=1.2)
    legend(x="topleft",
           legend=colnames(x=x$PCCBs)[-1],
           col=colrs, lty=1, lwd=1, bty="n")
    ##  GC composition of the entire set of reads.
    plot(x$GCs$density,
         bty="n",
         type="l", lwd=1,
         xlim=c(0, 1),
         ann=FALSE, axes=FALSE,
         col=rgb(red=0, green=114, blue=178, maxColorValue=255))
    lines(density(x=rnorm(n=length(x=x$GCs$frequency),
                          mean=mean(x=x$GCs$frequency),
                          sd=sd(x=x$GCs$frequency)))[1:2],
          xlim=c(0, 1),
          lwd=1,
          col=rgb(red=213, green=94, blue=0, maxColorValue=255))
    axis(side=1,
         at=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         labels=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         lwd=0.8)
    axis(side=2,
         at=c(0.0, max(x=x$GCs$density[, 2])/4 * 1:4),
         labels=round(x=c(0.0, max(x=x$GCs$density[, 2])/4 * 1:4), digits=2),
         las=1, lwd=0.8)
    title(main="GC composition of reads", cex.main=1.5)
    title(xlab="GC frequency", line=2.5, cex.lab=1.2)
    title(ylab="Density", line=2.8, cex.lab=1.2)
    legend(x="topleft",
           legend=c("theoretical", "empirical"),
           col=c(rgb(red=213, green=94, blue=0, maxColorValue=255),
                 rgb(red=0, green=114, blue=178, maxColorValue=255)),
           lty=1, lwd=1, bty="n")
    suppressWarnings(expr=legend(x="topright",
                                 legend=paste("KS test: p = ",
                                 ks.test(x=x$GCs$frequency, y="pnorm")$p.value,
                                 sep=""),
                                 lty=0, bty="n"))
    ##  Title, subtitle, sub-subtitle & footnote.
    mtext(text="Quality of the raw reads. Summary plots",
          side=3,
          line=3.5,
          cex=1.1,
          col="black",
          font=2,
          outer=TRUE)
    mtext(text=sprintf("Sample: %s", x$SN),
          side=3,
          line=2,
          cex=0.95,
          col="black",
          outer=TRUE)
    mtext(text=sprintf(paste("Date & Time:",
                             format(x=Sys.time(), "%b %d %Y %X"),
                             sep=" ")),
          side=3,
          line=0.5,
          cex=0.8,
          col="black",
          outer=TRUE)
    note <- "Generated by assessQRawReads() & reportQAResults()"
    mtext(text=sprintf(note),
          side=1,
          line=2,
          cex=0.7,
          col="black",
          outer=TRUE)
    ##  Summarization the low-complexity of reads (using dusty scores).
    plot(x$DSs$density,
         bty="n",
         type="l", lwd=1,
         xlim=c(2, 5),
         ann=FALSE, axes=FALSE,
         col=rgb(red=0, green=114, blue=178, maxColorValue=255))
    axis(side=1,
         at=c(2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0),
         labels=c(2.0, 2.5, 3.0, 3.5,  4.0, 4.5, 5.0),
         lwd=0.8)
    axis(side=2,
         at=c(0.0, max(x=x$DSs$density[, 2])/4 * 1:4),
         labels=round(x=c(0.0, max(x=x$DSs$density[, 2])/4 * 1:4), digits=2),
         las=1, lwd=0.8)
    title(main="Low-complexity of reads", cex.main=1.5)
    title(xlab=expression("Complexity, log"[10] * " (dusty scores)"),
          line=2.75, cex.lab=1.2)
    title(ylab="Density", line=3, cex.lab=1.2)
    legend(x=3.3, y=max(x=x$DSs$density[, 2]),
           legend=c("minimum:", "Q1:", "median:", "Q3:", "maximum:"),
           lty=0, bty="n")
    legend(x=4.1, y=max(x=x$DSs$density[, 2]),
           legend=round(x=log10(x=x$DSs$metrics), digits=2),
           lty=0, bty="n")
    rect(xleft=2.0, ybottom=0, xright=3.0, ytop=max(x=x$DSs$density[, 2]),
         density=20, border=NA, lwd=0.3,
         col=rgb(red=0, green=158, blue=115, maxColorValue=255))
    ##  Frequency of reads.
    barplot(formula=x$FRs[, 3] ~ x$FRs[, 1], data=x$FRs,
            axes=FALSE, ann=FALSE, ylim=c(0, 1), border=NA,
            col=colorRampPalette(c(rgb(red=213,
                                       green=94,
                                       blue=0,
                                       maxColorValue=255),
                                   rgb(red=230,
                                       green=159,
                                       blue=0,
                                       maxColorValue=255)))(nrow(x=x$FRs)))
    axis(side=2,
         at=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         labels=c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
         las=1, lwd=0.8)
    title(main="Frequency of reads", cex.main=1.5)
    title(xlab="Occurrence of reads",
          line=2.5, cex.lab=1.2)
    title(ylab="Frequency", line=3, cex.lab=1.2)
    ##  Contamination of reads with adapters.
    if (!is.null(x=nrow(x=x$ASs))){
        colrs <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288",
                   "#AA4499", "#44AA99", "#999933", "#882255", "#661100",
                   "#6699CC", "#888888")
        matplot(x$ASs[, -1],
                ann=FALSE, 
                axes=FALSE,
                ylim=c(0, 0.35),
                type="l", lty=1, lwd=1,
                col=colrs[1:ncol(x=x$ASs[, -1])])
        axis(side=1,
             at=1:length(x=x$ASs[, 1]),
             labels=FALSE,
             lwd=0.8)
        axis(side=2,
             at=c(0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35),
             labels=c(0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35), las=1,
             lwd=0.8)
        text(x=seq(from=1, to=length(x=x$ASs[, 1]), by=2),
             par("usr")[3] - 0.028, offset=-0.5,
             labels=x$ASs[, 1][seq(from=1, to=length(x=x$ASs[, 1]), by=2)],
             cex=0.9, srt=55, pos=2, xpd=TRUE)
        title(main="Adapter contaminations", cex.main=1.5)
        title(xlab="Cycles", line=3.8, cex.lab=1.2)
        title(ylab="Adapter frequency", line=3, cex.lab=1.2)
        legend(x="topleft",
               legend=colnames(x=x$ASs)[-1],
               cex=0.8,
               lty=1, lwd=1,
               col=colrs[1:ncol(x=x$ASs[, -1])],
               bty="n")
    }
    ##  Contamination of reads with foreign sequences.
    if (!is.null(x=nrow(x=x$FSs))){
        colrs <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288",
                   "#AA4499", "#44AA99", "#999933", "#882255", "#661100",
                   "#6699CC", "#888888")
        matplot(x$FSs[, -1],
                ann=FALSE, 
                axes=FALSE,
                ylim=c(0, 0.35),
                type="l", lty=1, lwd=1,
                col=colrs[1:ncol(x=x$FSs[, -1])])
        axis(side=1,
             at=1:length(x=x$FSs[, 1]),
             labels=FALSE,
             lwd=0.8)
        axis(side=2,
             at=c(0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35),
             labels=c(0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35), las=1,
             lwd=0.8)
        text(x=seq(from=1, to=length(x=x$FSs[, 1]), by=2),
             par("usr")[3] - 0.028, offset=-0.5,
             labels=x$FSs[, 1][seq(from=1, to=length(x=x$FSs[, 1]), by=2)],
             cex=0.9, srt=55, pos=2, xpd=TRUE)
        title(main="Foreign sequence contaminations", cex.main=1.5)
        title(xlab="Cycles", line=3.8, cex.lab=1.2)
        title(ylab="Sequence frequency", line=3, cex.lab=1.2)
        legend(x="topleft",
               legend=colnames(x=x$FSs)[-1],
               cex=0.8,
               lty=1, lwd=1,
               col=colrs[1:ncol(x=x$FSs[, -1])],
               bty="n")
    }
    ##  Title, subtitle, sub-subtitle & footnote.
    mtext(text="Quality of the raw reads. Summary plots (continuation)",
          side=3,
          line=3.5,
          cex=1.1,
          col="black",
          font=2,
          outer=TRUE)
    mtext(text=sprintf("Sample: %s", x$SN),
          side=3,
          line=2,
          cex=0.95,
          col="black",
          outer=TRUE)
    mtext(text=sprintf(paste("Date & Time:",
                             format(x=Sys.time(), "%b %d %Y %X"),
                             sep=" ")),
          side=3,
          line=0.5,
          cex=0.8,
          col="black",
          outer=TRUE)
    note <- "Generated by assessQRawReads() & reportQAResults()"
    mtext(text=sprintf(note),
          side=1,
          line=2,
          cex=0.7,
          col="black",
          outer=TRUE)
    suppressMessages(expr=dev.off())
}
